--NDefines.NCategory.Define = x
NDefines.NDiplomacy.MIN_RELATIONS_TO_ALLY = -200
NDefines.NDiplomacy.MONTHS_BEFORE_TOTAL_OCCUPATION = 12
NDefines.NCountry.PS_REPLACE_RIVAL = 50
NDefines.NCountry.MAX_IDEA_GROUPS_FROM_SAME_CATEGORY = 0.40